export const SET_IMAGE = 'SET_IMAGE'
export const SET_USERNAME = 'SET_USERNAME'
export const SET_SETTINGS_STATE = 'SET_SETTINGS_STATE'
export const SET_BIO = 'SET_BIO'
export const SET_EMAIL = 'SET_EMAIL'
export const SET_PASSWORD = 'SET_PASSWORD'